import { NextResponse } from "next/server";

import type { Place } from "../../../types/places";

const places: Place[] = [
  {
    id: "cpm:tokyo:owner-cafe-1",
    name: "Satoshi Coffee",
    country: "JP",
    city: "Tokyo",
    address: "1-1 Chiyoda, Tokyo",
    lat: 35.68,
    lng: 139.76,
    category: "cafe",
    verification: "owner",
    accepted: ["BTC", "BTC@Lightning", "ETH"],
    website: "https://satoshi-coffee.example.com",
    twitter: "@satoshi_coffee",
    instagram: "@satoshi.coffee",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "cpm:newyork:community-diner-1",
    name: "Liberty Diner",
    country: "US",
    city: "New York",
    address: "100 Liberty St, New York, NY",
    lat: 40.71,
    lng: -74.0,
    category: "diner",
    verification: "community",
    accepted: ["BTC", "USDT"],
    website: null,
    twitter: "@libertydiner",
    instagram: null,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "cpm:paris:directory-bistro-1",
    name: "Bistro du Coin",
    country: "FR",
    city: "Paris",
    address: "10 Rue de Paris, Paris",
    lat: 48.85,
    lng: 2.35,
    category: "restaurant",
    verification: "directory",
    accepted: ["BTC"],
    website: "https://bistro.example.fr",
    twitter: null,
    instagram: "@bistro.coin",
    updatedAt: new Date().toISOString(),
  },
  {
    id: "cpm:sydney:unverified-bookstore-1",
    name: "Harbour Books",
    country: "AU",
    city: "Sydney",
    address: "5 Harbour Rd, Sydney",
    lat: -33.86,
    lng: 151.2,
    category: "bookstore",
    verification: "unverified",
    accepted: ["BTC", "ETH"],
    website: null,
    twitter: null,
    instagram: null,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "cpm:toronto:owner-bakery-1",
    name: "Maple Bakery",
    country: "CA",
    city: "Toronto",
    address: "50 King St, Toronto",
    lat: 43.65,
    lng: -79.38,
    category: "bakery",
    verification: "owner",
    accepted: ["BTC@Lightning"],
    website: "https://maple-bakery.example.ca",
    twitter: null,
    instagram: "@maplebakery",
    updatedAt: new Date().toISOString(),
  },
];

export async function GET() {
  return NextResponse.json(places);
}
