import { NextResponse } from "next/server";

import type { Place } from "../../../types/places";

const places: Place[] = [
  {
    id: "cpm:tokyo:owner-cafe-1",
    name: "Satoshi Coffee",
    country: "JP",
    city: "Tokyo",
    address: "1-1 Chiyoda, Tokyo",
    lat: 35.68,
    lng: 139.76,
    category: "cafe",
    verification: "owner",
    about: "A cozy Bitcoin-first cafe serving specialty coffee and fresh pastries.",
    accepted: ["BTC", "BTC@Lightning", "ETH"],
    website: "https://satoshi-coffee.example.com",
    phone: "+81-3-1234-5678",
    twitter: "@satoshi_coffee",
    instagram: "@satoshi.coffee",
    images: [
      "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=1200&q=80",
    ],
    updatedAt: new Date().toISOString(),
  },
  {
    id: "cpm:newyork:community-diner-1",
    name: "Liberty Diner",
    country: "US",
    city: "New York",
    address: "100 Liberty St, New York, NY",
    lat: 40.71,
    lng: -74.0,
    category: "diner",
    verification: "community",
    about: "Classic American diner with a crypto-friendly checkout experience.",
    accepted: ["BTC", "USDT"],
    website: null,
    phone: "+1-212-555-0199",
    twitter: "@libertydiner",
    instagram: null,
    images: [
      "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80",
    ],
    updatedAt: new Date().toISOString(),
  },
  {
    id: "cpm:paris:directory-bistro-1",
    name: "Bistro du Coin",
    country: "FR",
    city: "Paris",
    address: "10 Rue de Paris, Paris",
    lat: 48.85,
    lng: 2.35,
    category: "restaurant",
    verification: "directory",
    about: "French bistro listed by the directory with seasonal menus.",
    accepted: ["BTC"],
    website: "https://bistro.example.fr",
    phone: "+33-1-42-68-53-00",
    twitter: null,
    instagram: "@bistro.coin",
    images: [],
    updatedAt: new Date().toISOString(),
  },
  {
    id: "cpm:sydney:unverified-bookstore-1",
    name: "Harbour Books",
    country: "AU",
    city: "Sydney",
    address: "5 Harbour Rd, Sydney",
    lat: -33.86,
    lng: 151.2,
    category: "bookstore",
    verification: "unverified",
    about: null,
    accepted: ["BTC", "ETH"],
    website: null,
    phone: null,
    twitter: null,
    instagram: null,
    images: [
      "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1507842217343-583bb7270b66?auto=format&fit=crop&w=1200&q=80",
    ],
    updatedAt: new Date().toISOString(),
  },
  {
    id: "cpm:toronto:owner-bakery-1",
    name: "Maple Bakery",
    country: "CA",
    city: "Toronto",
    address: "50 King St, Toronto",
    lat: 43.65,
    lng: -79.38,
    category: "bakery",
    verification: "owner",
    about: "Family-run bakery famous for maple-infused pastries.",
    accepted: ["BTC@Lightning"],
    website: "https://maple-bakery.example.ca",
    phone: "+1-416-555-0130",
    twitter: null,
    instagram: "@maplebakery",
    images: [
      "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=1200&q=80",
    ],
    updatedAt: new Date().toISOString(),
  },
];

export async function GET() {
  return NextResponse.json(places);
}
